### ISSUE TITLE
setHeader Function not setting header

### ISSUE THREAD

**Issue by nkarman** [infinitered/apisauce#118] opened 2017-07-20 22:39 UTC
Hey there @skellock ,

I am trying to override my default headers assigned at apisauce.create() for one specific request. I tried using the api.setHeader and api.setHeaders functions. I need to set the header to Content-Type multipart/form-data.

Ive included a screenshot of my request headers, after attempting to modify with setHeader. 

var body = new FormData()
    body.append('file', photo)
    api.setHeader({'Content-Type': 'multipart/form-data'})
    const response = api.put(`/user/photo/${id}`, body, {headers: {'Content-Type': 'multipart/form-data'}})
    return response

Thanks in advance for your help!

![screen shot 2017-07-20 at 5 36 31 pm](https://user-images.githubusercontent.com/21283068/28441818-616354f0-6d72-11e7-8db9-b98c535e75f2.png)

**Comment by skellock** [comment] 2017-07-21 02:11
Evening!  I think you want `setHeaders` instead of `setHeader` here. You can use `setHeader` but the interface is 2 strings, not an object. That where that `[object Object]` is coming from. 

i think you can remove that line entirely looking at your code tho.

**Comment by robinheinze** [comment] 2019-01-17 17:36
@AlexCppns Can you give a bit more context about where/when you're invoking each of those lines?

**Comment by jkeam** [comment] 2019-03-12 21:17
I can't replicate this issue either.  Here is how I'm testing it (using apisauce 1.0.2):

```
// app.js
const apisauce = require('apisauce')
const http = require('http')

const protocol = 'http'
const API_KEY = 'AWESOME_KEY'
const PORT = '8080'
const ENDPOINT = `localhost:${8080}`

// start server
const server = http.createServer()
server.on('request', (request, response) => {
  console.log(request.headers)
}).listen(PORT)

// start client
const api = apisauce.create({
  baseURL: `${protocol}://${ENDPOINT}`,
  timeout: 30000,
  headers: { "Authorization": `BEARER ${API_KEY}`}
})
api.get('/')
```

**Comment by jkeam** [comment] 2019-03-12 21:25
I was unable to reproduce the bug also.  Here is my test (using v1.0.2):

```javascript
// app.js
const apisauce = require('apisauce')
const http = require('http')

const PORT = '8080'

// start server
const server = http.createServer()
server.on('request', (request, response) => {
  console.log(request.headers)
}).listen(PORT)

// start client
const api = apisauce.create({
  baseURL: `http://localhost:${PORT}`,
  timeout: 30000,
  headers: { "Authorization": 'BEARER OLD_TOKEN'}
})

api.get('/')
api.setHeader('Authorization', 'BEARER NEW_TOKEN')
api.get('/')
```

Console
```
> node ./app.js

{ accept: 'application/json',
  'content-type': 'application/json',
  authorization: 'BEARER OLD_TOKEN',
  'user-agent': 'axios/0.18.0',
  host: 'localhost:8080',
  connection: 'close' }
{ accept: 'application/json',
  'content-type': 'application/json',
  authorization: 'BEARER NEW_TOKEN',
  'user-agent': 'axios/0.18.0',
  host: 'localhost:8080',
  connection: 'close' }
```

**Comment by jkeam** [comment] 2019-03-13 15:10
@AlexCppns are you still encountering issues or can we close this ticket?

**Comment by tsiareshchankau** [comment] 2019-07-01 09:37
> @AlexCppns are you still encountering issues or can we close this ticket?

I've just encountered this issue. apisauce@1.0.2 
```
api.setHeader('Content-Type', 'application/merge-patch+json')
```
did not work for me

**Comment by robinheinze** [comment] 2019-08-23 21:17
@tsiareshchankau Sorry for the delay. Are you still having the issue with `setHeader`? If so, can you provide a reproducible example app? Either a public repo, or using [Snack](https://snack.expo.io)?

**Comment by afsanefda** [comment] 2019-12-16 11:52
I also have this problem!
```

const { create } = require('apisauce');
const request = create({
    baseURL,
});

// server middleware used to add required headers to request
const serverRequestModifier = req => {
    const cookies = new Cookies(req.headers.cookie);
    const accessToken = cookies.get('_cm_token');
    const authorization = accessToken ? `Token ${accessToken}` : null;

    if (authorization) {
        request.setHeaders({ Authorization: authorization });
    }
    request.setHeaders({ Context: cookies.application_name });
};
```

**Comment by teachdugsimt** [comment] 2021-01-12 08:12
I have this problem too. when i try to upload image with formData. I can't add "Content-Type": "multipart/form-data" to header

**Comment by absmugz** [comment] 2021-03-19 06:29
@teachdugsimt did you come right ?

**Comment by absmugz** [comment] 2021-03-29 19:17
no response after 11 days, closing this as its not an issue

**Closed by absmugz** 2021-03-29 19:17 UTC
Labels: help wanted, question
