### ISSUE TITLE
NETWORK_ERROR after call setHeader method

### ISSUE THREAD

**Issue by elviocb** [infinitered/apisauce#211] opened 2019-04-18 00:53 UTC
I have couple tests running on my app. After I test the user login I have to set a new header with "Authorization": "Bearer ...".

I call the method from the apisauce instance:   api.setHeader("Authorization", "Bearer ..."). After I do that all requests return NETWORK_ERROR.

**Comment by jkeam** [comment] 2019-05-13 17:11
Possible duplicate of https://github.com/infinitered/apisauce/issues/118?

Can you provide code samples and a way to reproduce what you are seeing?

**Closed** 2021-08-20 17:34 UTC
Labels: need repro steps
